config/routes.rb
Rails.application.routes.draw do
	root to: 'tasks#index'
	
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :users_admin, :controller => 'users'

   resources :tasks
   resources :likes
   post 'likes/like_post',  to: 'likes#like_post'

   resources :comments
   post 'comments/add_comments', to: 'comments#add_comments'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :task
	belongs_to :user

	def self.build_comments_hash(comment_params, current_user)
		comment_params.merge!({user_id: current_user.id})
		comment = Comment.create(comment_params)
		comments_hash = {}
		comments_hash[:task_container_id] = "task-comments-container_#{comment_params['task_id']}"
		comments_hash[:comments] = Comment.where(task_id: comment_params["task_id"]).to_a
		comments_hash[:task_id] = comment_params["task_id"]
		comments_hash[:desc_id] = "desc_#{comment_params['task_id']}"
		comments_hash[:comments_count_id] = "comments_count_#{comment_params['task_id']}"
    comments_hash[:comments_count] = comments_hash[:comments].present? ? comments_hash[:comments].count : 0


		unless comment.save
			comments_hash[:error] = comment.errors
		end
		comments_hash
	end
end

app/models/like.rb
class Like < ApplicationRecord

	validates_presence_of :task, :user
	validates_uniqueness_of :task, scope: :user

	belongs_to :user
	belongs_to :task

	def self.like_post(like_params)
		like_obj = Like.includes(:task, :user).where(like_params)
		like = false		
		task_id = like_params[:task_id] if like_params[:task_id].present?
		if like_obj.present?
			if Like.destroy(like_obj.first.id)
				status = 200
			end
		else
			like_obj = Like.create(like_params)
			if like_obj.save 
				status = 200
			end
			like = true
		end

		like_objs = Like.where(task_id: task_id).all
		like_count = like_objs.count

		{status: status, like: like, like_count: like_count}
	end
end

app/models/task.rb
class Task < ApplicationRecord

	validates_presence_of :description, :creator
	validates_uniqueness_of :created_at, scope: :creator_id

	belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
	has_many :likes
	has_many :comments

	def self.build_task_hash(current_user)
		tasks_array = []
		tasks = Task.includes(:likes, :creator, :comments).all

		tasks.each do |task|
			task_hash = {}
			task_hash[:id] = task.id
			task_hash[:description] = task.description
			task_hash[:creator] = task.creator.name
			task_hash[:created_at] = task.calculated_posted_ago_time
			user_likes = task.likes.select {|like| like.user_id == current_user.id}
			task_hash[:likes_count] = task.likes.present? ? task.likes.count : 0
			task_hash[:comments_count] =  task.comments.present? ? task.comments.count : 0
      

			task_hash[:user_like_status] = user_likes.present? 
			task_hash[:comments] = task.comments
			tasks_array << task_hash
		end
		tasks_array
	end

	def calculated_posted_ago_time
		posted_ago_time = ''
		 posted_ago_hours = ((Time.now - self.created_at) / 1.hour).round
		 posted_ago_minutes = ((Time.now - self.created_at) / 1.minute).round

		 if posted_ago_hours > 0
		   posted_ago_time = posted_ago_hours.to_s + ' hours'
		 elsif posted_ago_minutes > 0
		   posted_ago_time = posted_ago_minutes.to_s + ' minutes'
		 else
		   posted_ago_seconds = ((Time.now - self.created_at) / 1.second).round
		   posted_ago_time = posted_ago_seconds.to_s + ' seconds'
		 end

		 posted_ago_time
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes
  has_many :tasks
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	 before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name ])
    #in keys you list all the input you want to accept.
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_params, except: [:index, :new, :add_comments]
	skip_before_action :verify_authenticity_token, only: [:add_comments]


	def index
		@comments = Comment.all
	end

	def new
		@comment = Comment.new
	end

	def add_comments
		@comment_resp = Comment.build_comments_hash(JSON.parse(params[:comment].to_s), current_user)

		respond_to do |format|
      format.js       
    end
	end

	private

	def set_params
		@comment_params = params.require(:comment).permit(:description, :task_id)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_params
	skip_before_action :verify_authenticity_token, only: [:like_post]

	def like_post
		response_json = Like.like_post(@like_params)	
		render :json => response_json.to_json
	end

	private

	def set_params
		@like_params = params.require(:like).permit(:task_id, :user_id)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :set_params, except: [:index, :new, :show, :edit]


	def index
		@tasks = Task.build_task_hash(current_user)
	end

	def new
		@task = Task.new
	end

	def create
		@task_params.merge!({creator_id: current_user.id})
		@task = Task.create(@task_params)

		if @task.save
			flash[:success] = "Task created Successfully"
			redirect_to tasks_path
		else
			flash[:error] = "Something went wrong. Try again"
			render :new
		end
	end

	private

	def set_params
		@task_params = params.require(:task).permit(:description)
	end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

	private

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,
    	:email, :password, :password_confirmation])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, 
    	:password_confirmation, :current_password) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def show
		@user = User.find_by(id: params[:id])
	end

	def edit

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/add_comments.js.erb
$("#<%= @comment_resp[:task_container_id] %>").html("<%= escape_javascript(render partial: 'tasks/comments', locals: { comments: @comment_resp[:comments], task_id: @comment_resp[:task_id] } ) %>"); 
$("#<%= @comment_resp[:comments_count_id] %>").text("<%= @comment_resp[:comments_count] %>");

$("#<%= @comment_resp[:desc_id] %>").value("");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatIDidToday</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="left left-header">
      </div>

      <div class="right right-header">
        <ul class="header-right-ul zero-margin">
          <% if current_user %>
            <li class="pointer-cursor">  <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            <li class="pointer-cursor"><%= link_to(image_tag("minion.png"), {action: 'show', controller: 'users', id: current_user.id}, class: 'action-icons') %></li>
          <% else %>
            <li class="pointer-cursor">Log In </li>
          <% end %>
          <li>
        </ul>
      </div>
    </header>

    <div class="main-container">
      <%= yield %>
    </div>

    
  </body>
</html>

app/views/tasks/_comments.html.erb
<div class="comments-div">
	<% if comments.present? %>
	<% comments.each do |comment| %>
		<div class="comment-div">
			<div><img src="/assets/user.png" class="comment-img">
			<p class='comment-desc'><%= comment.description %></p></div>
			<p class="height-10">User: <%= comment.user.name %></span>
				<span class="right">Commented On: <%= comment.created_at.strftime("%d %b %y") %></span>		
			</p>
		</div>
	<% end %>
	<% end %>
</div>
<div class="comments-form">
				<%= form_for :comment, url: "comments/add_comments", remote: true, html: { id: 'comment-form' } do |form| %>

				  <%= form.hidden_field :task_id, value: task_id %>
				  <div class="search-fields">
				  	<%= form.text_area :description, id: "desc_#{task_id}" %>
				  </div>

				  <div>
				  	<%= form.submit 'Comment', id: 'ad-comment-btn', remote: true, 'data-task-id' => task_id, click: 'form_action(this);' %>
				  </div>
				<% end  %>

</div>

app/views/tasks/index.html.erb
<% if @tasks.present? %>

	<% @tasks.each do |task| %>
		<div class='task-container'>
			<p><%= task[:description] %></p>
			<p class="height-10">
				<span class="left">Posted <%= task[:created_at] %></span>
				<span class="right">User: <%= task[:creator] %></span>
			</p>

			<p class="height-20">
				<span class="right">
				<% if task[:user_like_status] %>
				<span class="like-btn" data-task-id= "<%= task[:id] %>" data-user-id="<%= current_user.id %>"><%= image_tag("like.png")%><span><%= task[:likes_count] %></span></span>
				<% else %>
					<span class="like-btn" data-task-id= "<%= task[:id] %>" data-user-id="<%= current_user.id %>"><%= image_tag("unlike.png") %><span><%= task[:likes_count] %></span></span>
				<% end %>
				<span class="comments-icon"><%= image_tag('comments.png') %><span id=<%="comments_count_#{task[:id]}" %>><%= task[:comments_count] %></span></span>
			</span>
			</p>
    
    <div class='task-comments-container'>
    	<div id=<%= "task-comments-container_#{task[:id]}" %>>
			  <%= render 'comments', comments: task[:comments], task_id: task[:id] %>

			</div>	
		</div>		

		</div>
	<% end %>

<% else %>
	<p> No Tasks added for today <p>
<% end %>

<%= link_to 'Add Task', new_task_path, class: 'action-btn', id: 'add-task-btn' %>

app/views/tasks/new.html.erb
<%= form_for @task do |t| %>

  <div class='form'>
		 
		<div class="form-fields">
			<%= t.label 'Description' %>
			<%= t.text_area :description %>
		</div>

		<%= t.submit 'Create', class: 'action-btn' %>

	</div>

<% end %>

app/views/users/show.html.erb
<div class="global-display">

	<div class="page-header">
		<%= link_to image_tag("edit.png"), {action: 'edit', controller: 'users'}, class: 'action-icons' %>
	</div>	

	<div class="form-fields">
	<p class="label">Name:</p>
	<p class="disp-data"><%= @user.name %></p></div>

	<div class="form-fields"><p class="label">Project:</p>
	<p class="disp-data"><%= @user.role.name %></p></div>

</div>